import React, { useState, useEffect, useMemo } from 'react';
import { BrainCircuit, AlertTriangle, Lightbulb, ShieldAlert, Bot, Activity } from 'lucide-react';
import SectionWrapper from './SectionWrapper';
import { getAIInsight } from '../services/aiInsightService';

export default function AICommodityIntelligence({ alerts }) {
  const [selectedKomoditas, setSelectedKomoditas] = useState('');
  const [loading, setLoading] = useState(false);
  const [briefing, setBriefing] = useState(null);
  const [error, setError] = useState(null);
  
  // Cache to prevent re-generation delays
  const [cache, setCache] = useState({});

  const availableKomoditas = useMemo(() => {
    if (!alerts) return [];
    return [...new Set(alerts.map(a => a.komoditas))].sort();
  }, [alerts]);

  useEffect(() => {
    if (availableKomoditas.length > 0 && !selectedKomoditas) {
      setSelectedKomoditas(availableKomoditas[0]);
    }
  }, [availableKomoditas, selectedKomoditas]);

  useEffect(() => {
    if (!selectedKomoditas || !alerts) return;

    if (cache[selectedKomoditas]) {
      setBriefing(cache[selectedKomoditas]);
      setError(null);
      return;
    }

    let isMounted = true;
    
    async function loadBriefing() {
      setLoading(true);
      setError(null);

      try {
        const relevantAlerts = alerts
          .filter(a => a.komoditas === selectedKomoditas)
          .sort((a, b) => b.kenaikan_pct - a.kenaikan_pct);
        
        const primaryAlert = relevantAlerts[0];
        
        if (!primaryAlert) {
          throw new Error("No data for selected commodity");
        }

        const payload = {
          commodity: selectedKomoditas,
          current_price: primaryAlert.harga_sekarang || 0,
          forecast_price: primaryAlert.prediksi_7h || 0,
          change_percent: primaryAlert.kenaikan_pct || 0,
          recommendation_data: primaryAlert.ai_reasoning || "Fluktuasi pasar normal."
        };

        const result = await getAIInsight(payload);
        
        if (isMounted) {
          setCache(prev => ({ ...prev, [selectedKomoditas]: result }));
          setBriefing(result);
        }
      } catch (err) {
        if (isMounted) {
          console.error("AI Insight Error:", err);
          setError("AI briefing temporarily unavailable.");
        }
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    }

    loadBriefing();

    return () => {
      isMounted = false;
    };
  }, [selectedKomoditas, alerts, cache]);

  if (!alerts || alerts.length === 0) return null;

  return (
    <SectionWrapper
      icon={Bot}
      title="Executive AI Briefing"
      badge="AZURE OPENAI"
      subtitle="Generated by Azure OpenAI GPT-4.1-mini"
      rightContent={
        <>
          <span style={{ fontSize: 13, color: '#64748B', fontWeight: 600 }}>Pilih Komoditas:</span>
          <select 
            value={selectedKomoditas} 
            onChange={(e) => setSelectedKomoditas(e.target.value)}
            style={{ 
              padding: '8px 16px', borderRadius: 8, border: '1px solid #CBD5E1', 
              background: 'white', fontSize: 14, fontWeight: 700, color: '#0F172A',
              outline: 'none', cursor: 'pointer', minWidth: 200
            }}
          >
            {availableKomoditas.map(k => (
              <option key={k} value={k}>{k}</option>
            ))}
          </select>
        </>
      }
    >
      <div style={{ minHeight: 300 }}>
        {loading ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
            <div style={{ fontSize: 14, color: '#64748B', fontStyle: 'italic', display: 'flex', alignItems: 'center', gap: 8 }}>
              <Activity size={16} className="animate-pulse" /> Generating Executive AI Briefing...
            </div>
            <div className="skeleton" style={{ height: 100, borderRadius: 8 }} />
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
              <div className="skeleton" style={{ height: 160, borderRadius: 8 }} />
              <div className="skeleton" style={{ height: 160, borderRadius: 8 }} />
            </div>
          </div>
        ) : error ? (
          <div style={{ padding: 40, textAlign: 'center', color: '#EF4444', fontSize: 15, background: '#FEF2F2', borderRadius: 10, border: '1px solid #FECACA' }}>
            <AlertTriangle size={24} style={{ margin: '0 auto 12px auto' }} />
            {error}
          </div>
        ) : briefing ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
            
            {/* Executive Summary */}
            <div style={{ background: '#F0F9FF', border: '1px solid #BAE6FD', padding: 24, borderRadius: 10 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
                <BrainCircuit size={18} color="#0284C7" />
                <span style={{ fontSize: 13, color: '#0369A1', fontWeight: 800 }}>SUMMARY</span>
              </div>
              <div style={{ fontSize: 15, color: '#0C4A6E', lineHeight: 1.6, fontWeight: 500 }}>
                {briefing.summary}
              </div>
            </div>

            {/* 2 Columns */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 20 }}>
              
              {/* Risk Factors */}
              <div style={{ background: '#FEF2F2', padding: 20, borderRadius: 10, border: '1px solid #FECACA' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
                  <ShieldAlert size={18} color="#EF4444" />
                  <span style={{ fontSize: 13, color: '#B91C1C', fontWeight: 800 }}>RISK</span>
                </div>
                <div style={{ fontSize: 14, color: '#7F1D1D', lineHeight: 1.5 }}>
                  {briefing.risk}
                </div>
              </div>

              {/* Recommended Action */}
              <div style={{ background: '#F0FDF4', padding: 20, borderRadius: 10, border: '1px solid #BBF7D0' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
                  <Lightbulb size={18} color="#10B981" />
                  <span style={{ fontSize: 13, color: '#14532D', fontWeight: 800 }}>RECOMMENDATION</span>
                </div>
                <div style={{ fontSize: 14, color: '#14532D', lineHeight: 1.5 }}>
                  {briefing.recommendation}
                </div>
              </div>

            </div>
          </div>
        ) : null}
      </div>
    </SectionWrapper>
  );
}
