import React from 'react';
import { Bot, TrendingUp, AlertTriangle, Lightbulb } from 'lucide-react';

export default function AIInsightCard({ insight, loading, error, komoditas }) {
  return (
    <div className="ai-insight-box" style={{ marginTop: '20px' }}>
      <div className="ai-insight-header">
        <Bot size={18} color="#2563EB" />
        <span className="ai-insight-title">🤖 AI Insight — Analisis {komoditas}</span>
      </div>
      <div className="ai-insight-body">
        {loading ? (
          <div style={{ color: 'var(--text-muted)', fontStyle: 'italic', padding: '10px 0' }}>
            Generating AI Insight...
          </div>
        ) : error ? (
          <div style={{ color: '#EF4444', fontStyle: 'italic', padding: '10px 0' }}>
            ⚠️ AI Insight temporarily unavailable.
          </div>
        ) : insight ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontWeight: 600, color: '#1E40AF', marginBottom: '4px' }}>
                <TrendingUp size={16} /> <span>Ringkasan</span>
              </div>
              <p style={{ margin: 0, color: 'var(--text-main)', lineHeight: 1.5 }}>{insight.summary}</p>
            </div>
            
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontWeight: 600, color: '#B91C1C', marginBottom: '4px' }}>
                <AlertTriangle size={16} /> <span>Risiko</span>
              </div>
              <p style={{ margin: 0, color: 'var(--text-main)', lineHeight: 1.5 }}>{insight.risk}</p>
            </div>
            
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontWeight: 600, color: '#15803D', marginBottom: '4px' }}>
                <Lightbulb size={16} /> <span>Rekomendasi</span>
              </div>
              <p style={{ margin: 0, color: 'var(--text-main)', lineHeight: 1.5 }}>{insight.recommendation}</p>
            </div>
          </div>
        ) : null}
      </div>
      <div className="ai-insight-footer">
        📌 Generated by Azure OpenAI GPT-4.1-mini | Model: LSTM + Prophet | Last Updated: {new Date().toLocaleDateString('id-ID', { day: '2-digit', month: 'long', year: 'numeric' })}
      </div>
    </div>
  );
}
